{% set name = "skyllh" %}
{% set version = "24.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skyllh-{{ version }}.tar.gz
  sha256: 60d969fcd38bd7b832a7b0374da8d39a0bcef5a7dbde63c9d9afc8986e3c1b36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - versioneer
    - pip
  run:
    - python >={{ python_min }}
    - astropy
    - numpy
    - scipy
    - tqdm

test:
  imports:
    - skyllh
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/icecube/skyllh
  summary: The SkyLLH framework is an open-source Python3-based package licensed under the GPLv3 license. It provides a modular framework for implementing custom likelihood functions and executing log-likelihood ratio hypothesis tests. The idea is to provide a class structure tied to the mathematical objects of the likelihood functions.
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tomaskontrimas
